sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-049
env:
  global:
    -
      # LTD_AWS_ID
      secure: PHOGpFx/Aj/Nvj00c1izwwGUCtbXFL4q6kdEWHW0a7AgIfcryaW82jiiELOsK68XLUKMRQHF2CV7P99VVgvxJG6MXfDhVkbQ3oMs7LCPfz3YnH7ATDY7UMSGz3xsnpE8hNUQ9Btrjn2c0Nk913Y/rPGaGM1S82ZZAKbbMBAytTXNuv3jrC+joXpqdMjvVDxuV6SR4cXTWiApcrGlcID876rVz8ilrbf0B5JJNTHVqPksRO+fWi/mZa9gCngIwZxsWvdf1K2KB9t103zD+h1A1SnSWF2fHvpCE1izSGVUWq4W0N9sC6nmLgB91SOXUSyFQjh08CXhcvdXebaSrjh3r75T40reNR14kyC56Y1WvaNNLT0SJ9BqY6AIUTiv2B1eeq5fBZ5bU+onqxNUNZSoa3/tBVj0qoBY/rlXL5K5xdggwfptfbsavVEsxoNgIt98Ln9S/ezYus8kECKe4h6qnlh4wwABQAnCokGaSF0gkzxdt43cefMfrVJLrhI/4mOt8XA2PwoxTPYl60tWvEmcHoAjZLoE7ptqtBxqlXFeSQSdtnTRWFvw9Y75pL8yT+olrF1+/iJmWCCHugieMtxJfuAkTIPG4I0yAeJFYvnI4nORSvUABS7QS2paKJ/LcxNrN7LdJaROSM1HOexveAcpQ87XfVqpH0gL8y4sQOsAkzQ=
    -
      # LTD_AWS_SECRET
      secure: N/IMVRQZ8hGyLRiWNba9xYjF1De9dX60KwrhU1d9Bi4CEBXk4s5Z4iD20BwG//eToGi7mO8A3A0xdgDa9Ew7CJ09Uco63mebKAwnK55dqnZ+FcWhlJG90ciAXCh94wQLIpCk88MIYofNHka17eUxsi7Rm3ywgDYlPotvRm0DEmdsRWF4lbryCr+kBOW63Cso3mVaUuchxA9JRs/w6UGnD7uIsSAYi48hjaHjJqyZRtcq0vCsFgp+0p0qwrCddiy5tUrnkZSVZhBXK54cbUSSmfA+K0cfmBGfjWFU/QGuSzeL05qmp4tSy6LoRm4dkMSDi/2b40HjT3dpkiQPrWup0kZgPLNrPhFt/UmGLzlaC5UCFgdZECr4E4Dhq/Me2cN19s+YJTZs7JgpiyTpsu56adzeLKsQfhMCp1GYwjZZN+YxyIx84jHTP72Hxdn6sq3F3D/+YoYq7q8u/ZWOYuEy+8c745ZCB4j7gPsP/78P3EcywVtDuJ1sPOIFLrjLltoaktYUmPDrDzenCLmFqVQKFTm6mpnj4HgHk7mB4Ph+9Zyp6KhYc8snPbk3yNv35VjZ5B8zlFHBjNoNdL27m6pJeeDspx905/N811ETwaCFkLlyCdEzqsXYuWTR1n8Wyk00tvggpRzlEO8UfIPXkobjz7azFH6d6cRtGPO5Yy8YskM=
    -
      # LTD_USERNAME
      secure: e5TaAd0xL0DWNkmWktmdUSkYjkS/I7/I1I4WBDBIh6ccsUpLEQ0N4JMbae/+aOPP3leCoDb/SViS16i2mYrQesQHqjJGSqm+oI4Cq6hJkpVf+9K7E+0mZsjcl+tL2458EPfLffTj/3x07vzAVJzWyqNEoN2jBBd3OzLcS2ctaiwD5t9LHLMZdUf+xKFIjweDzZCgH6lVqSNEyzQYlaDKLC1ckm91fwGqtbvOJygNpFBrjIv+K5OiEfMDLwWVkONA/qg0J/hSbcQC1fdawduVu6rss/KFQirfDx42xvxBuDU2cNy93PwpZA7OFpFO/uK09HtI3+ClnYDqMkbxegDArI0oAzBYdjPE8yT3nV4GDqppfV3Q7sDNUdj2FDyJ9oYkABwYAhVjaymL3oYuXRjEwcQQm2GxWMxyaBVlw4SEVEEPVnMPI5m/Gpfb910gN0UhHtJ7EJhTdlw5QyyQLLc3rLJcb2v/A9I4z84yaT1jUeCwXxyYM8uYQ/ForLhRfSmsCvUMe/wp1gZguVG7b6l1Tb3r1g105UJooKEQAhvAdimi/KswpRHcosHifQSS8rcxSd3hGagTcBkv40Yz4ORX8m5YTH7YkAX3H8GWdxc8wtSgxzY9pcQXdI50Jo1HjrBCubzUDjv5Q42mIHyc/wjfedcgfl9tkJtSFiRYj66uQ+Y=
    -
      # LTD_PASSWORD
      secure: Ovzn40+LU59XcIMz9q1Odi4ayup6kGodZoYE1+MT1a9BTE+knqXclrUJwAGEANe1wbjHbHfl6+mv91LOmJSRdyEg9Jc87scv0SHwgBLWnFZY4dC6fQIC1eR6Iy8hOoSb5smYjY5IzKd5TGAAnxY36Es11HiWT8jA+vCaX7iTbyzO7e0AJANtR7tRMCQxVy0YN6QzGYbsrr4mLPifkbOXH2ksDDWGjjItR7N1D36/EaHTWJc832233hwuurhi8Yoo2madeHRtVeV4zR9X4N9NK5u95P6sH5znSxzseNYK2VmcsvsM2NGkSpj8up1mQ0GH2SRrl2+ApBpPVf0nwNeNbXBIdG+Fcy1/4B78XMJKVPBXnXA2UYq6eOvBqM8oTA53vr0Jb414MmG30Rin3J7QT0kJgclJnEJhzmHHMacPit7yLxrKpjVDBp9qumvx6vyPUDLSodKgnbF+rkH1WCo02GiTbUQTIgVYmchE3tN5Mg2ZJ0hVNa7WfMUxc2urt7kmyDpH83v2QNTpDXUFi/8am4SmjDmcI3wKw/Sa5/LCvuYoUeTlEawaLUAWqXaJ2ijIn7L+r/G72Fye56N+5SAboU1MtpUaUHe74xUY5RD9hUPLnNR8VGyexeRfV8/pc7Igpb+KZQtp/B1jRowOoiG4bHSWIpleSKIycAOmLCxjfi4=
